# Generated by Django 2.1.3 on 2018-11-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(verbose_name='update date')),
                ('fossil_ratio', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='fossil ration')),
                ('nuclear_ratio', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='nuclear ration')),
                ('renewable_ratio', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='renewable ratio')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(verbose_name='update date')),
                ('temp', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='temperature')),
                ('temp_min', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='minimum temperature')),
                ('temp_max', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='maximum temperature')),
                ('cond_id', models.IntegerField(default=0, verbose_name='condition id')),
                ('cond_text', models.TextField(verbose_name='condition text')),
                ('description', models.TextField(verbose_name='description')),
            ],
        ),
    ]
