# Generated by Django 2.1.3 on 2018-11-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(unique=True, verbose_name='update date')),
                ('fossil_ratio', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='fossil ration')),
                ('nuclear_ratio', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='nuclear ration')),
                ('renewable_ratio', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='renewable ratio')),
            ],
            options={
                'ordering': ['-dt'],
            },
        ),
        migrations.CreateModel(
            name='WeatherMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(unique=True, verbose_name='update date')),
                ('temp', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='temperature')),
                ('temp_min', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='minimum temperature')),
                ('temp_max', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='maximum temperature')),
                ('cond_id', models.IntegerField(default=0, verbose_name='condition id')),
                ('cond_text', models.TextField(blank=True, default='', verbose_name='condition text')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
            ],
            options={
                'ordering': ['-dt'],
            },
        ),
        migrations.AddIndex(
            model_name='weathermeasure',
            index=models.Index(fields=['dt'], name='data_api_v1_dt_9e5822_idx'),
        ),
        migrations.AddIndex(
            model_name='energymeasure',
            index=models.Index(fields=['dt'], name='data_api_v1_dt_329eec_idx'),
        ),
    ]
