version: '2'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["./manage.py", "runserver", "0.0.0.0:80"]
    image: rtt/api
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./src:/rtt
